In [1]:
import numpy as np
import time

The elements of a vector arre all the same type
The number of elements in the array is reffered to as dimension or rank (for the math lads)


In [2]:
# Numpy routines which allocate memory and fill arrays with value
a = np.zeros(4)
print(f"np.zeroes(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,))
print(f"np.zeroes(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a =  np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}") 

np.zeroes(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeroes(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.86828779 0.30872505 0.70707753 0.9471996 ], a shape = (4,), a data type = float64


In [3]:
# the above thing but do not accept shape as input argument
a = np.arange(4.)
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# what's the difference b/w np.random.rand and np.random_sample????

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.68037115 0.96582536 0.33762528 0.16552066], a shape = (4,), a data type = float64


In [4]:
#numpy routines which allocate memory and fill with user sepcified values
a = np.array([5,4,3,2])
print(f"np.array([5,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4.,3.,2.])
print(f"np.array([5.,4.,3.,2.]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


np.array([5,4,3,2]): a = [5 4 3 2], a shape = (4,), a data type = int64
np.array([5.,4.,3.,2.]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


Operation on vectors : 
1) Indexing:
Indexing means referring to an element of an array by its position within the array.


In [5]:
a = np.arange(10)
print(a)
#accessing an element returns a scalar
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}")

print(f'a[-1] = {a[-1]}')

try:
    c = a[10]
except Exception as e:
    print("The error message u gonna see is")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2
a[-1] = 9
The error message u gonna see is
index 10 is out of bounds for axis 0 with size 10


2) Slicing:
Slicing means getting a subset of elements from an array based on their indices.
Slicing creates an array of indices using a set of three vlaues (start: stop: step)

In [7]:
a = np.arange(10)
print(f'a     = {a}')

c = a[2:7:1]
print(c)

c = a[2:7:2]
print(c)

c = a[3:]
print(c)

c = a[:3]
print(c)

c = a[:]
print(c)

a     = [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


Single vector operations

In [8]:
a = np.array([1,2,3,4])
print(a)

b = -a
print(b)

#sum of all elements of a returns a scalar
b = np.sum(a)
print(b)

b = np.mean(a)
print(b)

b = a**2
print(b)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


Vector element-wise operations

In [9]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(f'binary oeprators work element wise : {a+b}')

binary oeprators work element wise : [0 0 6 8]


In [10]:
#for this to work correctly the vectors must be of the same size
#try a mismatched vector operaion
c = np.array([1,2])
try:
    d = a+c
except Exception as e:
    print("the errror message you'll see is ")
    print(e)

the errror message you'll see is 
operands could not be broadcast together with shapes (4,) (2,) 


Scalar vector operations

In [11]:
#vectors can be 'scaled' by scalar values. a scalar value is just a number. The scalar multiplies all the elements of a vector
a = np.array([1,2,3,4])

b = 5 * a
print(b)

[ 5 10 15 20]


Vector Dot Product:


The dot product multiplies the vlaues in two vectors element-wise and them sums the resut. It requires the dimensions of the two vectors to be the same.

In [12]:
# Let us try to implement it using for loop initally
def my_dot(a,b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [13]:
#test 1-d
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])
print(f'my_dot(a,b) = {my_dot(a,b)}')

my_dot(a,b) = 24


In [15]:
#trying same operation usoing np.dot
c = np.dot(a,b)
print(f'{c=}, {c.shape=}')
c  = np.dot(b,a)
print(f'{c=}, {c.shape=}')


c=24, c.shape=()
c=24, c.shape=()


NEEEEEEEED FOR SPEEEEEEEEEEEEEEED

In [16]:
np.random.seed(1)
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f'{c=}')
print(f'duration of the vecotrized version: {1000*(toc-tic):.4f} ms')

tic = time.time()
c = my_dot(a,b)
toc = time.time()

print(f'{c=}')
print(f'duration of the loop version: {1000*(toc-tic):.4f} ms')
del(a)
del(b)
#they're removing the big arrays from memroy

c=249825.02337924895
duration of the vecotrized version: 13.1905 ms
c=249825.02337923684
duration of the loop version: 865.8659 ms


The reason the vectorized version is faster is cuz numpy makes better use of available data prallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in ML where data sets are often very large

Vecotr Vector operations

In [18]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1],w)
print(c)
print(f'{X[1].shape=}')
print(f'{w.shape=}')
print(f'{c.shape=}')

4
X[1].shape=(1,)
w.shape=(1,)
c.shape=()


Matrices

In notation, matrices are denoted with capitol, bold letter such as X. 
m is oftenthe number of rows, while n is the number of coloumns. 

Matric creation-

In [19]:
a = np.zeros((1,5))
print(f'{a.shape=}, {a=}')

a = np.zeros((2,1))
print(f'{a.shape=}, {a=}')

a = np.random.random_sample((1,1))
print(f'{a.shape=}, {a=}')


a.shape=(1, 5), a=array([[0., 0., 0., 0., 0.]])
a.shape=(2, 1), a=array([[0.],
       [0.]])
a.shape=(1, 1), a=array([[0.03762516]])


In [21]:
#numpy routines which fill with user specifies values
a = np.array([[5], [4], [3]])
print(f'{a.shape=}, {a=}')
a = np.array([[5],
             [4],
             [3]])
print(f'{a.shape=}, {a=}')


a.shape=(3, 1), a=array([[5],
       [4],
       [3]])
a.shape=(3, 1), a=array([[5],
       [4],
       [3]])


Operations on matrices

In [22]:
#Indexing 
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
#The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")


a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [23]:
#slicing
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
